backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - label: Pages
    name: pages
    files:
      - label: About page
        name: about
        file: src/about/text.md
        fields:
          - {label: HTML, name: html, widget: markdown}
  - label: Products
    name: products
    folder: src/products
    create: true
    extension: json
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "desc", widget: "markdown"}
      - {label: "Quantity", name: "stock", widget: "number", default: 1}
